name: 학생개발단 가입
description: 경북소프트웨어고 학생개발단에 가입하기 위한 이슈입니다.
title: "가입신청"
labels: ["regist"]
assignees:
  - pmh-only
body:
  - type: markdown
    attributes:
      value: |
        다음의 정보를 제출하여 학생개발단에 가입하고자 합니다.
  - type: input
    id: regist_year
    attributes:
      label: 입학년도
      description: 입학년도를 선택해 주세요.
      options: ["2021", "2022", "2023"]
    validations:
      required: true
  - type: input
    id: class_id
    attributes:
      label: 학번
      description: 학번을 입력해주세요 (4자리)
      placeholder: ex. 1209
    validations:
      required: true
  - type: input
    id: netkey
    attributes:
      label: 네트워크 키
      description: |
        네트워크 키를 입력해주세요.
        네트워크 키는 [여기](https://netkey.gbsw.hs.kr/) 에서 얻을 수 있습니다.
      placeholder: eyJ....
    validations:
      required: true
