name: Regist issue
on:
  issues:
    types:
      - labeled
jobs:
  regist:
    if: github.event.label.name == 'regist'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get source
        uses: actions/checkout@v2
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            네트워크 키 검증이 시작되었습니다. :sparkles:
      - name: Install dependency
        run: |
          cd actions/regist
          npm i
      - name: Run validation
        id: valid
        run: |
          cd actions/regist
          node . '${{ toJSON(github.event.issue.body) }}' ${{ secrets.JWT_TOKEN }}
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        if: steps.valid.outputs.netkey_valid == 'true'
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            네트워크 키 검증에 성공하였습니다. :tada:
      - name: Invite user
        if: steps.valid.outputs.netkey_valid == 'true'
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.PMH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/GBSWHS/invitations \
            -d '{"invitee_id":"${{ github.event.issue.user.login }}"} || exit 0'
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        if: steps.valid.outputs.netkey_valid != 'true'
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            네트워크 키가 잘못되었거나 만료되었습니다. :rotating_light:
            [이곳](https://github.com/GBSWHS/.github/issues/new?assignees=pmh-only&labels=regist&template=regist.yml&title=%EA%B0%80%EC%9E%85%EC%8B%A0%EC%B2%AD#new_issue)에서 다시시도해 주세요
      - name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}
